name: Test Registry Agency

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Registry Agency
        run: |
          curl -i "https://portal.registryagency.bg/CR/api/Deeds/205159453?entryDate=2026-09-19T20%3A59%3A59.999Z&loadFieldsFromAllLegalForms=false"