name: Test Registry Agency

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Registry Agency
        run: |
          curl -i "https://portal.registryagency.bg/CR/api/Deeds/Summary?page=1&pageSize=25&count=1&name=&ident=205159453&selectedSearchFilter=1&includeHistory=true"